name       : wlc
version    : 0.0.10
release    : 3
source     :
    - https://github.com/Cloudef/wlc/releases/download/v0.0.10/wlc-0.0.10.tar.bz2 : f8273940eaceb0661d365d284aceef7cb0ca83e641b7722d818dcac464fb0b01
license    : MIT
component  : desktop.library
summary    : Wayland compositor library
description: |
    Wayland compositor library
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libinput)
    - pkgconfig(pixman-1)
    - pkgconfig(valgrind)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-image)
    - pkgconfig(xkbcommon)
    - doxygen
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
