name       : wlc
version    : 0.0.11
release    : 4
source     :
    - https://github.com/Cloudef/wlc/releases/download/v0.0.11/wlc-0.0.11.tar.bz2 : c2061f5d6c627688ea8b822ac5f4d3ba4d407b3f8d79267677ce4011b6390d22
license    : MIT
component  : desktop.library
summary    : Wayland compositor library
description: |
    Wayland compositor library
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libinput)
    - pkgconfig(pixman-1)
    - pkgconfig(valgrind)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-image)
    - pkgconfig(xkbcommon)
    - doxygen
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
